## Two functions (makeCacheMatrix and cachesolve) will
## cache the inverse of the given matrix

## makeCacheMatrix : It creates a matrix that will be able to
## cache its inverse
makeCacheMatrix <- function(a = matrix()) {

  ## Provides the inverse property
  j <- NULL
  
  ## STEP 1 : Set the value of the matrix
  set <- function(b) {
    a <<- b
    j <<- NULL  
}

  ## STEP 2 : Get the value of the matrix
  get <- function() a
        
  ## STEP 3 : Set the values of the inverse matrix
  setInverse <- function(inverse) j <<- inverse
        
  ## STEP 4 : Get the value of the inverse matrix
  getInverse <-function() j
        
  ## Generate a list for the function
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}
        
## cacheSolve : Calculates the inverse of the cache matrix
## that was generated by the first function
cacheSolve <- function(a, ...) {
        
  ## Return a matrix that is the inverse of 'a'
  j <- x$getInverse()
  if (!is.null(j)) {
    message("Processing...")
    return(j)
  }
        
  ## Get the matrix from the object
  m <- x$get()
        
  ## Generate the inverse matrix
  j <- solve(m, ...)
  x$setInverse(j)
  j
}

